/*
 * test_jitter.c — Receive-side jitter buffer (poc_jb_*).
 *
 * Drives the buffer with synthetic packets generated by the real
 * Opus codec, exercising in-order, out-of-order, dropped-frame, and
 * forced-advance paths. The codec's inband FEC (LBRR) is enabled
 * by default, so single-packet gaps recover via decode_fec().
 */

#ifdef HAVE_CONFIG_H
#include "config.h"
#endif
#include "poc_internal.h"
#include "poc_jitter.h"
#include <string.h>
#include <stdlib.h>
#include <math.h>

extern void test_begin(const char *name);
extern void test_assert(int cond, const char *msg);

#define RATE   24000
#define FRAME  480

/* Sink for poc_jb_emit. Records every emitted PCM frame in arrival
 * order so the test can assert on count, n_samples, and speaker_id. */
typedef struct {
    int       count;
    int       last_n_samples;
    uint32_t  last_speaker;
} jb_sink_t;

static void sink_emit(const int16_t *pcm, int n_samples,
                      uint32_t speaker_id, void *ud)
{
    (void)pcm;
    jb_sink_t *s = (jb_sink_t *)ud;
    s->count++;
    s->last_n_samples = n_samples;
    s->last_speaker = speaker_id;
}

/* Encode `n_packets` of synthetic tone using `codec` and write the
 * resulting bytes into pkts/lens. Caller must free pkts[i]. */
static void encode_n(poc_codec_t *codec, int n_packets,
                     uint8_t **pkts, int *lens)
{
    int16_t pcm[FRAME];
    for (int i = 0; i < FRAME; i++)
        pcm[i] = (int16_t)(8000.0 * sin(2.0 * 3.14159265 * 440.0 * i / RATE));
    for (int i = 0; i < n_packets; i++) {
        pkts[i] = malloc(POC_CODEC_MAX_ENCODED_SIZE);
        lens[i] = poc_codec_encode(codec, pcm, FRAME,
                                    pkts[i], POC_CODEC_MAX_ENCODED_SIZE);
    }
}

static void free_n(uint8_t **pkts, int n)
{
    for (int i = 0; i < n; i++) free(pkts[i]);
}

void test_jitter(void)
{
    /* In-order delivery: 5 packets, all should pop out as decoded. */
    {
        test_begin("jitter: in-order delivery emits all frames");
        poc_jb_t jb;
        poc_jb_init(&jb, 6);
        poc_codec_t *codec = poc_codec_create();
        uint8_t *pkts[5]; int lens[5];
        encode_n(codec, 5, pkts, lens);

        jb_sink_t sink = {0};
        for (int i = 0; i < 5; i++)
            poc_jb_push(&jb, codec, 1001, (uint16_t)(100 + i),
                        pkts[i], lens[i], sink_emit, &sink);

        test_assert(sink.count == 5, "5 frames out");
        test_assert(sink.last_n_samples == FRAME, "480 samples per frame");
        test_assert(sink.last_speaker == 1001, "speaker passed through");
        test_assert(jb.decoded == 5, "5 normal decodes");
        test_assert(jb.fec_recovered == 0, "no FEC needed");

        free_n(pkts, 5);
        poc_codec_destroy(codec);
        poc_jb_destroy(&jb);
    }

    /* Out-of-order: 1, 3, 2, 4 — the buffer reorders before emitting. */
    {
        test_begin("jitter: out-of-order packets reorder before emit");
        poc_jb_t jb;
        poc_jb_init(&jb, 6);
        poc_codec_t *codec = poc_codec_create();
        uint8_t *pkts[4]; int lens[4];
        encode_n(codec, 4, pkts, lens);

        jb_sink_t sink = {0};
        poc_jb_push(&jb, codec, 1001, 1, pkts[0], lens[0], sink_emit, &sink);
        test_assert(sink.count == 1, "1 emitted after seq 1");
        poc_jb_push(&jb, codec, 1001, 3, pkts[2], lens[2], sink_emit, &sink);
        /* seq 2 is missing — FEC recovery should fire from packet 3
         * because Opus encodes LBRR for frame 2 inside packet 3.
         * That gives us 2 (FEC), then 3 (normal) = +2 emits. */
        test_assert(sink.count == 3, "FEC recovered seq 2 then emitted seq 3");
        test_assert(jb.fec_recovered == 1, "one FEC recovery");
        /* Late packet 2 should be dropped (already past it). */
        poc_jb_push(&jb, codec, 1001, 2, pkts[1], lens[1], sink_emit, &sink);
        test_assert(sink.count == 3, "late packet 2 dropped, no new emit");
        test_assert(jb.dropped_late == 1, "late packet counted");
        /* Packet 4 in normal path. */
        poc_jb_push(&jb, codec, 1001, 4, pkts[3], lens[3], sink_emit, &sink);
        test_assert(sink.count == 4, "seq 4 emitted normally");

        free_n(pkts, 4);
        poc_codec_destroy(codec);
        poc_jb_destroy(&jb);
    }

    /* Duplicate detection. */
    {
        test_begin("jitter: duplicate packets are dropped");
        poc_jb_t jb;
        poc_jb_init(&jb, 6);
        poc_codec_t *codec = poc_codec_create();
        uint8_t *pkts[2]; int lens[2];
        encode_n(codec, 2, pkts, lens);

        jb_sink_t sink = {0};
        /* Send same seq twice before the buffer drains. */
        poc_jb_push(&jb, codec, 1001, 50, pkts[0], lens[0], sink_emit, &sink);
        /* That emit drained slot 50 immediately (initialized → next_seq=50,
         * matches, decode, advance to 51). For a true dup we need the
         * packet to land BEFORE its own slot drains. Use a packet that
         * gets buffered: send seq 53 first (jumps ahead), then 50 dup. */
        poc_jb_t jb2;
        poc_jb_init(&jb2, 6);
        jb_sink_t sink2 = {0};
        poc_jb_push(&jb2, codec, 1001, 50, pkts[0], lens[0], sink_emit, &sink2);
        /* Next push of same seq 50 — late since next_seq advanced to 51. */
        poc_jb_push(&jb2, codec, 1001, 50, pkts[0], lens[0], sink_emit, &sink2);
        test_assert(jb2.dropped_late == 1, "second seq 50 marked as late");

        free_n(pkts, 2);
        poc_codec_destroy(codec);
        poc_jb_destroy(&jb);
        poc_jb_destroy(&jb2);
    }

    /* Forced advance: a packet far in the future bounds the buffer. */
    {
        test_begin("jitter: oversized seq jump force-advances");
        poc_jb_t jb;
        poc_jb_init(&jb, 4);  /* small ring */
        poc_codec_t *codec = poc_codec_create();
        uint8_t *pkts[2]; int lens[2];
        encode_n(codec, 2, pkts, lens);

        jb_sink_t sink = {0};
        /* First packet anchors next_seq = 200. */
        poc_jb_push(&jb, codec, 1001, 200, pkts[0], lens[0], sink_emit, &sink);
        /* Jump to 220 — 20 ahead of cap=4, must force-advance ~17 slots
         * via PLC, then emit packet 220 normally. */
        poc_jb_push(&jb, codec, 1001, 220, pkts[1], lens[1], sink_emit, &sink);
        test_assert(jb.forced_advance > 0, "forced advance fired");
        test_assert(sink.count >= 2, "frames emitted across the gap");

        free_n(pkts, 2);
        poc_codec_destroy(codec);
        poc_jb_destroy(&jb);
    }

    /* Speaker change resets the buffer. */
    {
        test_begin("jitter: speaker change resets next_seq and speaker_id");
        poc_jb_t jb;
        poc_jb_init(&jb, 6);
        poc_codec_t *codec = poc_codec_create();
        uint8_t *pkts[2]; int lens[2];
        encode_n(codec, 2, pkts, lens);

        jb_sink_t sink = {0};
        poc_jb_push(&jb, codec, 1001, 1, pkts[0], lens[0], sink_emit, &sink);
        test_assert(sink.last_speaker == 1001, "first speaker recorded");
        /* Different speaker, low seq — should reset and accept. */
        poc_jb_push(&jb, codec, 2002, 1, pkts[1], lens[1], sink_emit, &sink);
        test_assert(sink.last_speaker == 2002, "speaker rotated");
        test_assert(sink.count == 2, "both speakers' first frames emitted");

        free_n(pkts, 2);
        poc_codec_destroy(codec);
        poc_jb_destroy(&jb);
    }
}
