#ifndef LIBPOC_VERSION_H
#define LIBPOC_VERSION_H

#define LIBPOC_VERSION_MAJOR 1
#define LIBPOC_VERSION_MINOR 0
#define LIBPOC_VERSION_PATCH 0

#ifdef LIBPOC_GIT_HASH
#define LIBPOC_VERSION_STRING "1.0.0+" LIBPOC_GIT_HASH
#else
#define LIBPOC_VERSION_STRING "1.0.0"
#endif

#endif
